sudo: false
language: node_js
node_js:
- '6.0'
- '5.0'
before_script:
  - npm install -g frontplate-cli
script:
  - frp task clean
  - frp task sprite
  - frp task copy
  - frp task html
  - frp task script
  - frp task style
notifications:
  slack:
    secure: U1Ta+5fq1Np5Vig6D2qte0jvrnzHJc2DpKpgJSZOd8LGP3FWZ/t1vTT7sepY6WzMETuen0BGtO56wlCE2qFBAQUPIC5rkH71wy2hFE3WGjOuNSB6Sqpf9mfK6XvEQJRi9UDVlSDFuBHAftrnit855IyUEL7aZZWsvhdYUS+j4DQ=
